### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by thiagoc7** [thereactivestack/kickstart#13]
Hi @eXon, thanks for this awesome project!

do you plan to incluide integration tests?
I need same high level tests, without mocks or stubs.
If you need I can help, thanks!

**Comment by eXon** [comment]
Yes!!!!

Integration tests only need to test the backend because the unit test with React are pretty much testing everything the frontend has.

I am looking into integrating Velocity and add integration tests on the methods and subscriptions mainly. That way you could have 100% test coverage for the frontend and 100% test coverage for the backend.

I'll keep this open until this is done :) Thanks for asking.

**Comment by eXon** [comment]
If you have suggestions on how this should be done, let me know! I'm just learning how Velocity works so someone with a little bit of experience with that framework will definitively help

**Comment by thiagoc7** [comment]
Hi @eXon, I´m also learning React and Meteor...
But what I miss is a `user` level testing, like [capybara](https://github.com/jnicklas/capybara).
I found (zombie)[https://github.com/assaf/zombie], that seems to be a realy good anternative on js. I just don´t know if it´s going to work out of the box on this stack.

Just an unrelated question, to don´t open another issue.
I rebuilt this app, for learning, with:
- (react-mixins)[https://github.com/brigand/react-mixin], so (TodoApp)[https://github.com/thereactivestack/kickstart/blob/master/react/todo/TodoApp.jsx] can be a `class`
- (radium0[https://github.com/FormidableLabs/radium], for inline conditional styles
would like me to `PR` this changes?

Cheers!

**Comment by eXon** [comment]
Hey @thiagoc7 

Because of the way React is working, we don't really need integration tests like that. You can already simulate user interaction with the `TestUtils.Simulate.click()` and everything.

What's missing is some tests on the Meteor methods and subscriptions. For right now, that part is mocked. We need to test it inside a real Meteor environment.

For the react-mixins, I don't want to add any degree of complexity for the project so I said no before. But the more I look at it and the more I think it makes more sense to use this. If you would like to make a PR, I will be interested to merge it.

For radium, I would prefer to stick to require CSS files for now. I don't think radium is something everyone will want to use.

**Comment by eXon** [comment]
This has been done. You can look at the kickstart-simple or kickstart-hugeapp :) Forgot to close this one
