### ISSUE TITLE
blank todo app

### ISSUE THREAD

**Issue by holyxiaoxin** [thereactivestack/kickstart#19]
After `cloning`, `npm install` and `./scripts/run-dev.sh`, localhost:3000 shows blank page.

Am I missing something? I'm running node v4.1.1.

**Comment by john-osullivan** [comment]
It's because the current path spec for TodoApp doesn't match the index route.  The top component specifies path: '/', and the TodoApp child route specifies '/' as well.  For some reason, Todo's route doesn't get matched.  Took me a while to figure out that was the case, but if you change TodoApp's route to 'todo' and load localhost:3000/todo, you'll see the app render.

Still figuring out how to get the index path to load properly, though, haven't worked that out.

**Comment by eXon** [comment]
The fix was simply to get rid of path: '/' on the main component. We don't need that.

**Comment by john-osullivan** [comment]
When I get rid of path:'/' on the main component, the to-do app still doesn't render.  It's being hit by the routes, but the console.log()s say that the required prop children was not specified.  The TodoApp is unchanged from the example here, maybe the indexRoute isn't getting triggered?

**Comment by holyxiaoxin** [comment]
I had to change path to '/todo' for todo's routes in order to get it to work at localhost:3000/todo.

Maybe a recent commit messed something. Integration testing is good.

**Comment by john-osullivan** [comment]
Figured out my issue!  My IDE had been marking ES6 classes which were marked with @ReactMixin as an error if they were the default export.  This was making the IDE complain about an error:

`@ReactMixin.decorate(ReactMeteorData)
export default class Main extends Component {`

Whereas this was totally fine:

`@ReactMixin.decorate(ReactMeteorData)
export class Main extends Component {`

I've never used ES6 classes before so I'm still working out how the importing works, but my bug was that making this change meant that Main had to be imported like this:

`import {Main} from './components/Main';`

instead of like this:

`import Main from './components/Main';`

Changing the way the import was written out got rid of my bug, and the To-Do page is now loading from the index route without any other issues.

**Comment by eXon** [comment]
Good to know you found the fix. This means when exporting in Main.jsx, you had `export class Main ...` instead of `export default class Main ...`.
